### DISCUSSION TITLE
Add a negate flag

### DISCUSSION THREAD

**Discussion by petemounce** [codingjoe/relint#110] [Ideas]
I would like to add a rule that fails when a regex is _not_ matched, for example a `VERSION` file containing a `v1.0.0` and a pattern like `^v` (because a v prefix on a semver is not valid).

**Comment by petemounce** [comment]
```yaml
---
# https://semver.org/#is-v123-a-semantic-version
- name: VERSION files must contain semver.
  # LOLWAT? https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
  pattern: '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
  hint: "https://semver.org/#is-v123-a-semantic-version"
  filePattern: '.*VERSION'

- name: VERSION file contents must not be prefixed with a v
  pattern: '^v'
  hint: "https://semver.org/#is-v123-a-semantic-version"
  filePattern: '.*VERSION'
```

`cmd/VERSION`:

```
v0.1.1
```

I want that file to fail both rules, not just the 2nd one.
