### DISCUSSION TITLE
🐛 Linting rule should not trigger multiple times for the same line

### DISCUSSION THREAD

**Discussion by mroy-seedbox** [codingjoe/relint#115] [Q&A]
### Bug Description

Sometimes a rule can capture the same match multiple times.

### Expected Behavior

That should be counted as just one match.

### Version

3.3.1

### Stack trace

![Image](https://github.com/user-attachments/assets/8487e574-5f6a-445a-b092-c702442dc28d)

### Steps to Reproduce

```yml
- name: Jinja expressions should have a leading and trailing space
  pattern: '([{][{][^ ])|([^ ][}][}])'
  hint: "Add spaces before and after the curly braces: {{ code here }}"
```

And lint: `{{"hello world"}}`
