### ISSUE TITLE
Case insensitive flag?

### ISSUE THREAD

**Issue by tennox** [codingjoe/relint#17]
Could you add support for case insensitive flag?
Even the example you provided is quite awkward:
```yaml
- name: No ToDo
  pattern: '[tT][oO][dD][oO]'
```

maybe also just a flags field?

**Comment by tennox** [comment]
I just stumbled upon pre-commit docs' hint and though I'd try this:
```yaml
- name: No NOCOMMIT
  pattern: "(?i)NOCOMMIT" # case insensitive
  hint: Disallow committing files containing NOCOMMIT comment
```

And it works: :tada: 
```
imports/ui/components/stay-dialog/events/EventsTab.jsx:38 No NOCOMMIT
Hint: Disallow committing files containing NOCOMMIT comment
38>    // noCommit
```
