### ISSUE TITLE
Exclude specific files that would otherwise match a broader pattern

### ISSUE THREAD

**Issue by msladecek** [codingjoe/relint#8]
I work on a python repository and I'd like to use relint in pre-commit and CI pipeline to make sure nobody ever commits a `print` call, so I use this pattern specification:
```yaml
- name: Leftover print
  pattern: "print\\("
  filename:
    - "*.py"
```

However, there is one file in the root of the repo - `run.py` which contains a few startup scripts and it uses prints to give some runtime info to the users.

Is there any way I can define the `filename` pattern in a way to include all `.py` files _except_ `run.py`?
