### ISSUE TITLE
GitHub annotations are marking the wrong (shifted) line

### ISSUE THREAD

**Issue by amureki** [codingjoe/relint#98]
Hey!
Thank you for the package and for fixing #91, which introduced GitHub annotations! This is very neat.
I noticed a bug that, in some cases, it fails to assign an annotation to the right line. Here is an example:

```yml
- name: Do not use types in your names
  pattern: '_(date|time|datetime|duration)\s+'
  filePattern: (.*\.py)
  hint: |
    Please do not use types in your names.
    Instead, use the type hinting provided by Python.
    See also: https://www.youtube.com/watch?v=-J3wNP6u5YU&t=126s
  error: false
```

![CleanShot 2024-11-08 at 14 08 29@2x](https://github.com/user-attachments/assets/49e6a8fa-be40-4834-bbd7-332d34f79b92)

We can see that the warning is about the line 7; however, the annotation is set to line 8.
I am not yet sure what led to that, but maybe you have a quick idea.

**Comment by mroy-seedbox** [comment]
`\s` matches any whitespace or line terminator character.

Which means that it matches the newline between line 7 and 8. As a result, line 8 is included in the error.

**Comment by mroy-seedbox** [comment]
Try with this instead:
```yaml
- name: Do not use types in your names
  pattern: '(?m)_(date|time|datetime|duration)$'
  filePattern: (.*\.py)
  hint: |
    Please do not use types in your names.
    Instead, use the type hinting provided by Python.
    See also: https://www.youtube.com/watch?v=-J3wNP6u5YU&t=126s
  error: false
```

`(?m)` is a flag which allows start (`^`) and end (`$`) characters to match on line start & end instead of the entire file start & end.

Result:
![image](https://github.com/user-attachments/assets/0d23b1ce-c846-461f-92f8-75f5a5f7ccfe)
